services:
  test:
    image: phosphorgus/bt-dev
    container_name: baby_tracker-test
    working_dir: /app
    depends_on:
      - db-test
    ports:
      - 3000:3000
    environment:
      NODE_ENV: test
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    command: npm run test
    restart: "no"

  db-test:
    image: phosphorgus/bt-db
    container_name: baby_tracker-db-test
    environment:
      MONGO_INITDB_ROOT_USERNAME: superadmin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: babytracker
    ports:
      - 27017:27017
    volumes:
      - test-mongodb:/data/db
      - test-mongodb_config:/data/configdb
    restart: unless-stopped

volumes:
  node_modules: {}
  test-mongodb: {}
  test-mongodb_config: {}
