version: '3.9'

services:
  test:
    depends_on: 
      - db-test
    image: phosphorgus/bt-dev
    container_name: baby_tracker-test
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=test
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: npm run test
  db-test:
    image: phosphorgus/bt-db
    container_name: baby_tracker-db-test
    environment:
      MONGO_INITDB_ROOT_USERNAME: superadmin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: babytracker
    ports:
      - 27017:27017
    volumes:
      - test-mongodb:/data/db
      - test-mongodb_config:/data/configdb
      
volumes:
  node_modules:
  test-mongodb:
  test-mongodb_config:
